### ISSUE TITLE
FEATURE REQUEST: Handle it better when a column in DB has an uknown type

### ISSUE THREAD

**Issue by capaj** [romeerez/rake-db.js#1]
When running db pull on a project which uses citext I got this:
 ```
$ ts-node src/db/dbScripts.ts pull
/home/capaj/work-repos/official/official-graphql2/graphql/node_modules/rake-db/src/pull/structureToAst.ts:259
        throw new Error(
              ^
Error: Cannot handle column official.email_prefs.email: column type `citext` is not supported
    at pushTableAst (/home/capaj/work-repos/official/official-graphql2/graphql/node_modules/rake-db/src/pull/structureToAst.ts:259:15)
    at structureToAst (/home/capaj/work-repos/official/official-graphql2/graphql/node_modules/rake-db/src/pull/structureToAst.ts:92:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async pullDbStructure (/home/capaj/work-repos/official/official-graphql2/graphql/node_modules/rake-db/src/pull/pull.ts:15:15)
    at async rakeDb (/home/capaj/work-repos/official/official-graphql2/graphql/node_modules/rake-db/src/rakeDb.ts:33:7)
error Command failed with exit code 1.
```

ATM rake handles it by crashing.
I would want ideally to skip this field, emit a warning into the console and continue with generating the schema when a unknown data type is detected.

**Comment by romeerez** [comment]
I updated readme to point out that this is the old repo, new repo is in orchid-orm

**Comment by capaj** [comment]
should I reopen in orchid-orm?

**Comment by capaj** [comment]
@romeerez maybe deprecating this repo would be best? It can de done in github repo settings.

**Comment by romeerez** [comment]
But you already opened the same issue in there
